### ISSUE TITLE
Need to Specify the Type of Diodes

### ISSUE THREAD

**Issue by Quisette** [petercpark/The_Uni#1]
Recently I’ve self-printed some PCBs of your model, 
but I have not found any description about the type of the diode, including the voltage. This makes me unable to specify which diode to use. 
If able, please provide the specific diodes you use when soldering your pcbs.

Thanks

**Comment by petercpark** [comment]
Most SOD-123 diodes commonly used in keyboards work. I use SM4007PL but 1N4148W also works. You can find the LCSC part number of the diode I use in the [BOM](https://github.com/petercpark/The_Uni/blob/main/Gerbers/v2/unisplit_orthosteno_bom.csv)
